### ISSUE TITLE
Server crash when using node v0.10.31

### ISSUE THREAD

**Issue by tsuk13** [michaelwittig/node-q#24]
Hey just letting you know I was getting a server crash when running a query on a KDB server. It had no error message the app would just stop working. a "Count xxxxx" ran fine but a "select from xxxxx where i>0,i<=100" would crash the whole node server. This was on linux and node v0.10.31. I upgraded the server to the version of node I was running locally, v0.12.2 and everything is working fine now. Just thought you might want to take a look at your required node version in package.js

**Comment by michaelwittig** [comment]
Hi @tsuk13 
can you upload / send me the serialized data that you tried to send from q to nodejs ?
