### ISSUE TITLE
null for time type

### ISSUE THREAD

**Issue by ritalg** [michaelwittig/node-q#26]
Hi, I want to insert data from node-q to kdb table. One of the columns in the table is of type time. How can I  insert a null (0Nt) value in time column?

**Comment by michaelwittig** [comment]
you can either use a string like shown here:
```
con.k("sum 1 2 3", function(err, res) {
    if (err) throw err;
    console.log("result", res); // 6
});
```

or you can use the typed API as documented here: https://github.com/michaelwittig/node-q#types

if you can share the code you have at the moment this would help

**Comment by ritalg** [comment]
thanks for you help
