### ISSUE TITLE
passing an array or object where the only values are null fails serialization causes connection to lock up 

### ISSUE THREAD

**Issue by kevinykchan** [michaelwittig/node-q#29]
If we pass anything through node-q where all values are null (either an object or an array), serialization into q types fail and causes connection to kdb to lock up completely.

```
c.k('x', [null, null, null], (e,r) => console.log(e, r))
Error: bad type null

c.k('x', {hello: null, world: null}, (e,r) => console.log(e, r))
Error: bad type null
```

Any of these calls will lock up the socket completely.
It should correctly serialize the values in the list to ::

**Comment by michaelwittig** [comment]
released as node-q@2.2.2
