### ISSUE TITLE
Deserialization for remote compressed ipc calls sometimes fails

### ISSUE THREAD

**Issue by kevinykchan** [michaelwittig/node-q#30]
As shown through email communication with @michaelwittig. Unable to post test data here used to reproduce the issue as it may contain sensitive information.

**Comment by michaelwittig** [comment]
Released as node-q@2.2.3

**Comment by michaelwittig** [comment]
This should also have fixed #12

**Comment by kevinykchan** [comment]
Matt, the fix is working great. No more deserialization issues now

Thanks,
