### ISSUE TITLE
Unicode string turns into a messy code

### ISSUE THREAD

**Issue by liutongwei** [michaelwittig/node-q#35]
Examples:
```
var nodeq = require("node-q");

nodeq.connect({ host: "localhost", port: 5000 }, function(err, con) {
    if (err) throw err;
    console.log("connected");
    // interact with con like demonstrated below 
    con.k('aa:`$"你好"', function(err, res) {
        if (err) throw err;
        console.log("result", res); // 6 
    });
    con.close(function() {
        console.log("con closed");
    });
});
```
But when I look at the variable `aa` in q, it returns with a totally different string:

`浣犲ソ

How could I solve this problem?

**Comment by michaelwittig** [comment]
I can not really reproduce any issues with unicode? I adjusted your example slightly to fix a issue with the async code in your node.js example. I also return aa after the assignment in the q code.

```
nodeq.connect({ host: "localhost", port: 5000 }, function(err, con) {
    if (err) throw err;
    console.log("connected");
    con.k('aa:`$"你好"; aa', function(err, res) {
        if (err) throw err;
        console.log("result", res);
        con.close(function() {
            console.log("con closed");
        });
    });
});
```

outputs
```
connected
result 你好
con closed
```

what return do you expect from a variable assignment?

**Comment by liutongwei** [comment]
Hi, @michaelwittig Thanks for your reply. 

I could receive the same output as your reply from node side. But when I typed `aa` in q terminal, it returned with `浣犲ソ`.

![qq 20170922105115](https://user-images.githubusercontent.com/10570443/30727469-fbf03a4a-9f83-11e7-9029-01b674ef65b8.png)

The problem is that I would like to read a `.csv` file in q which contains unicode like Chinese characters, using the code:

```
CstInfo:("sdsssbsssssfs"; 1# ",")0: `CustomerInfo.csv
```

And it returns with the `CstInfo ` correctly like below:

![qq 20170922105856](https://user-images.githubusercontent.com/10570443/30727641-0d1faa2a-9f85-11e7-8df6-b719692a0e0b.png)

But when I use the nodeq command to fetch data from `CstInfo `:

```
nodeq.connect({ host: "localhost", port: 5000 }, function(err, con) {
    if (err) throw err;
    console.log("connected");
    con.k('1# select from CstInfo', function(err, res) {
        if (err) throw err;
        console.log("result", res);
        con.close(function() {
            console.log("con closed");
        });
    });
});
```
The output does not show correctly, seen the content surrounded by red lines (sorry for the mask):

![qq 20170922110756](https://user-images.githubusercontent.com/10570443/30727839-627d43c8-9f86-11e7-81be-9e6bf23998ba.png)

So is there any method I could take to solve this problem?

Thanks again for your reply.

**Comment by michaelwittig** [comment]
couldyou provide my one of those CstNames that is not working as text? I can not extract the test data from the image easily.

**Comment by liutongwei** [comment]
Hi, @michaelwittig. Thanks for your reply. I am sorry that I forgot to attach the csv file. Here is the  `CustomerInfo.csv` which contains Chinese characters. Maybe you could open it with charset `GBK` to see the correct demonstration as shown in the image above.

[CustomerInfo.zip](https://github.com/michaelwittig/node-q/files/1324441/CustomerInfo.zip)

And you could just copy the unicode string `广发证券股份有限公司（OTC）`to clipboard to use these characters.

It is so kind of you to spend your time on this problem.

**Comment by liutongwei** [comment]
Hi, @michaelwittig. 

Now I can solve the charset problem. The reason is because I save the `.csv` file using charset `GBK`. When I save it with charset `Unicode`, the output shows correctly.

![unnamed qq screenshot20170922202455](https://user-images.githubusercontent.com/10570443/30744359-511f2b5c-9fd4-11e7-9173-0a7b1c2e6e52.png)

But the Unicode string could not be shown as what it should be in the q terminal. 

![unnamed qq screenshot20170922203118](https://user-images.githubusercontent.com/10570443/30744547-1f2f25a6-9fd5-11e7-9a6f-a8892ff4e6bf.png)

This is a very tricky problem. I think it is not about node-q, but I should deal with `q`. 

Thank you so much. I do appreciate your time.
