### ISSUE TITLE
Command getting corrupted through serialisation?

### ISSUE THREAD

**Issue by richardbutler** [michaelwittig/node-q#8]
I'm trying to query a function, which would be called q-side like this (this would return me a table):

```
q) `.xyz.getTrades; `VOD.L, 2015.07.08; 0t; 2015.07.09; 24t; ()!()
```

However, I've tried a few variations, such as the below (and every permutation between symbols, date objects, strings, etc) with `nodeq.k` without success, but I'm not sure which part is getting corrupted as KDB errors are, well, you know :)

```
nodeq.k('.xyz.getTrades', ['`VOD.L', '2015.07.08', '0t', '2015.07.09', '24t', {}], function ...

nodeq.k('.xyz.getTrades', ['VOD.L', '2015.07.08', '0t', '2015.07.09', '24t', '()!()'], function ...

nodeq.k('`.xyz.getTrades', ['`VOD.L', new Date(2015, 6, 8), '0t', new Date(2015, 6, 9), '24t', {}], function ...

nodeq.k('`.xyz.getTrades' ['`VOD.L; 2015.07.08; 0t; 2015.07.09; 24t; ()!()'], function ...
```

And also the full command as a string:

```
nodeq.k('`.xyz.getTrades; `VOD.L; 2015.07.08; 0t; 2015.07.09; 24t; ()!()', function ...

nodeq.k('.xyz.getTrades; `VOD.L; 2015.07.08; 0t; 2015.07.09; 24t; ()!()', function ...
```

I get varying errors but mostly `badreq`. Is there something obvious that I'm doing wrong here?

**Comment by michaelwittig** [comment]
what about
```
nodeq.k(".xyz.getTrades[`VOD.L;2015.07.08;0t;2015.07.09;24t;()!()"]
````

**Comment by richardbutler** [comment]
No joy, but I did find out the cause of the problem. This one gets through:

```
nodeq.k('`xyz.getTrades', '`VOD.L', new Date(2015, 6, 8), '0t', new Date(2015, 6, 9), '24t', {}, function ...
```

But time values, e.g. `0t`, `24t`, are getting sent to Q as strings. How would you expect c.js to handle those?

**Comment by michaelwittig** [comment]
the problem is, that JavaScript does not have as much types as q have. e.g. we have no type for times. 

I made a slight mistake is my previous line (edited this one as well), this one should work:
`````
nodeq.k(".xyz.getTrades[`VOD.L;2015.07.08;0t;2015.07.09;24t;()!()]", function(err, res) { ... });
`````

Providing a string that is then evaluated as q code on the q side is at the moment the version that gives you the most control.

**Comment by richardbutler** [comment]
Bingo. Thanks!

**Comment by michaelwittig** [comment]
always happy to see someone using q/kdb+ :)
